#cloud-config

package_update: true
package_upgrade: true
package_reboot_if_required: false

manage-resolv-conf: true
resolv_conf:
  nameservers:
    - "8.8.8.8"
    - "8.8.4.4"

packages:
  - ca-certificates
  - curl

write_files:
  - path: /etc/systemd/system/vault.service
    permissions: 0644
    owner: root
    content: |
      [Unit]
      Description="HashiCorp Vault - A tool for managing secrets"
      Documentation=https://www.vaultproject.io/docs/
      Requires=network-online.target
      After=network-online.target
      ConditionFileNotEmpty=/etc/vault.d/vault.hcl
      StartLimitIntervalSec=60
      StartLimitBurst=3

      [Service]
      User=vault
      Group=vault
      ProtectSystem=full
      ProtectHome=read-only
      PrivateTmp=yes
      PrivateDevices=yes
      SecureBits=keep-caps
      AmbientCapabilities=CAP_IPC_LOCK
      CapabilityBoundingSet=CAP_SYSLOG CAP_IPC_LOCK
      NoNewPrivileges=yes
      ExecStart=/usr/bin/vault server -config=/etc/vault.d/vault.hcl
      ExecReload=/bin/kill --signal HUP $MAINPID 
      KillMode=process
      KillSignal=SIGINT
      Restart=on-failure
      RestartSec=5
      TimeoutStopSec=30
      StartLimitInterval=60
      StartLimitIntervalSec=60
      StartLimitBurst=3
      LimitNOFILE=65536
      LimitMEMLOCK=infinity

      [Install]
      WantedBy=multi-user.target
  - path: /etc/vault.d/vault.hcl
    permissions: 0644
    owner: root
    content: |
      storage "raft" {
        path = "/data/vault"
        node_id = "raft_node_1"
      }
      cluster_addr = "http://127.0.0.1:8201"
      api_addr = "http://127.0.0.1:8200"

      listener "tcp" {
        address     = "127.0.0.1:8200"
        tls_disable = 1
      }

      ui = true

runcmd:
  - curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
  - apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
  - apt-get update -y
  - apt-get install vault
  - vault
  - mkdir /data
  - mkdir /data/vault
  - chown -R vault:vault /data/vault
  - systemctl start vault.service
  - systemctl enable vault.service
  - gpg --keyserver keyserver.ubuntu.com --recv-key A9215275A11EAAC6
  - gpg --export A9215275A11EAAC6 | base64 > fr123k.asc
  - VAULT_ADDR=http://127.0.0.1:8200 vault operator init -key-shares=3 -key-threshold=2 -pgp-keys="fr123k.asc,fr123k.asc,fr123k.asc" -root-token-pgp-key="fr123k.asc"
