node ("packer") {
    stage('Checkout') {
        cleanWs()
        checkout scm
    }
    stage('Debug') {
        dir('aws/vault') {
            withCredentials([usernamePassword(credentialsId: 'aws-key-credentials', passwordVariable: 'PKR_VAR_aws_secret_key', usernameVariable: 'PKR_VAR_aws_access_key')]) {
                sh("printenv | sort")
                sh("make build")
            }
        }
    }
}
