#cloud-config

package_update: true
package_upgrade: true
package_reboot_if_required: false

manage-resolv-conf: true
resolv_conf:
  nameservers:
    - "8.8.8.8"
    - "8.8.4.4"

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common

write_files:
  - path: /etc/systemd/system/jocker.service.env
    permissions: 0644
    owner: root
    content: |
      ADMIN_PASSWORD=quai6Piexaiviequ
      SEED_JOB_GIT_REPO=fr123k/jocker-agents
      SEED_JOB_GROOVY_FILE=jenkins/pipeline-jobs.groovy
    # SEED_JOB_GIT_REPO=fr123k/jenkins-aws-pulumi
    # SEED_JOB_GROOVY_FILE=jenkins/pipeline-jobs.groovy
    # SEED_BRANCH_JOBS=fr/add_jenkinsfile
    # {{ AWS_KEY_ID }}
    # {{ AWS_KEY_SECRET }}
    # {{ ADMIN_PASSWORD }}
  - path: /etc/systemd/system/jocker.service
    permissions: 0644
    owner: root
    content: |
      [Unit]
      Description=Run an jocker container
      Author=Frank Ittermann
      Requires=docker.service
      After=docker.service

      [Service]
      TimeoutStartSec=0
      Restart=always
      ExecStartPre=-/usr/bin/docker rm -f jocker
      ExecStart=-/usr/bin/docker run --rm --memory 1g -p 50000:50000 -p 80:8080 --env-file /etc/systemd/system/jocker.service.env --name jocker fr123k/jocker
      ExecStartPost=/bin/sleep 180
      ExecStop=/usr/bin/docker stop -t 2 jocker

  - path: /etc/systemd/system/jocker-agent-pre.sh
    permissions: 0755
    owner: root
    content: |
      #!/bin/bash

      echo "Admin pass ${ADMIN_PASSWORD}"
      echo -n "AGENT_SECRET=" > /etc/systemd/system/jocker-agent.service.secret.env
      curl -L -s http://admin:${ADMIN_PASSWORD}@localhost:80/computer/docker-1/slave-agent.jnlp | sed "s/.*<application-desc main-class=\"hudson.remoting.jnlp.Main\"><argument>\([a-z0-9]*\).*/\1/" >> /etc/systemd/system/jocker-agent.service.secret.env

  - path: /etc/systemd/system/jocker-agent.service
    permissions: 0644
    owner: root
    content: |
      [Unit]
      Description=Run an jocker container
      Requires=jocker.service
      After=jocker.service

      [Service]
      Restart=always
      TimeoutStartSec=300
      EnvironmentFile=/etc/systemd/system/jocker.service.env
      EnvironmentFile=-/etc/systemd/system/jocker-agent.service.secret.env
      ExecStartPre=-/usr/bin/docker rm agent
      ExecStartPre=-/etc/systemd/system/jocker-agent-pre.sh ${ADMIN_PASSWORD}
      ExecStart=-/usr/bin/docker run --memory 3g --env-file /etc/systemd/system/jocker.service.env --name agent fr123k/jocker-agents-golang -url http://172.17.0.1:80 ${AGENT_SECRET} docker-1
      ExecStop=/usr/bin/docker stop -t 2 agent

runcmd:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  - add-apt-repository "deb [arch=amd64]
    https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - apt-get update -y
  - apt-get install -y docker-ce docker-ce-cli containerd.io
  - systemctl start docker
  - systemctl enable docker
  - systemctl daemon-reload
  - docker pull fr123k/jocker
  - docker pull fr123k/jocker-agents-golang
  - systemctl start jocker.service
  - systemctl enable jocker.service
  - systemctl start jocker-agent.service
  - systemctl enable jocker-agent.service
